lane :app do
  gitlab_get_max_version_branch(
    projectid: '849',
    host: gitlab_host,
    token: gitlab_token,
    search: '^master',
    regex: /^master_([1-9]\d|[1-9])(\.([1-9]\d|\d)){2,}$/ #=> master_x.y.z
  )
  master_branch = Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::GITLAB_GET_MAX_VERSIO_NBRANCH_RESULT]
  UI.important master_branch

end

lane :modules do
  gitlab_get_max_version_branch(
    via_tag: true,
    projectid: '16456',
    host: gitlab_host,
    token: gitlab_token,
    regex: /^([1-9]\d|[1-9])(\.([1-9]\d|\d)){2,}$/
  )
  master_branch = Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::GITLAB_GET_MAX_VERSIO_NBRANCH_RESULT]
  UI.important master_branch
end
