lane :test do
  gitlab_get_max_version_branch(
    projectid: '19320',
    host: 'https://git.in.xxx.com/api/v4',
    token: 'xxx',
    regex: %r(^master_([1-9]\d|[1-9])(\.([1-9]\d|\d)){2,}$) #=> master_x.y.z
  )
  pp Fastlane::Actions.lane_context[Fastlane::Actions::SharedValues::GITLAB_GET_MAX_VERSIO_NBRANCH_RESULT]
end
