lane :test do
  gitlab_get_max_version_branch(
    projectid: '19320',
    host: 'https://git.in.xx.com/api/v4',
    token: 'xxx',
    regex: %r(^master_([1-9]\d|[1-9])(\.([1-9]\d|\d)){2,}$) #=> master_x.y.z
  )
end
